



#3333333333333333333333333333333333 working production


# services:
#   app:
#     build:
#       context: .
#       dockerfile: dev.Dockerfile
#       args:
#         POSTGRES_PRISMA_URL: postgresql://postgres:postgres@db:5432/database_name
#         POSTGRES_PRISMA_URL_NON_POOLING: postgresql://postgres:postgres@db:5432/database_name
#     environment:
#       - NODE_ENV=development
#       - DATABASE_URL=postgresql://postgres:postgres@db:5432/database_name
#       - POSTGRES_PRISMA_URL=postgresql://postgres:postgres@db:5432/database_name
#       - POSTGRES_PRISMA_URL_NON_POOLING=postgresql://postgres:postgres@db:5432/database_name
#     volumes:
#       - .:/app
#       - /app/node_modules
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: database_name
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./ssl:/etc/nginx/ssl
#     depends_on:
#       - app
#     restart: always
# volumes:
#   db_data:

#3333333333333333333333333333333333 working end production




# ////////////////////////////////////////   working for production

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        POSTGRES_PRISMA_URL: postgresql://postgres:postgres@db:5432/database_name
        POSTGRES_PRISMA_URL_NON_POOLING: postgresql://postgres:postgres@db:5432/database_name
    env_file:
      - .env    
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/database_name
      - POSTGRES_PRISMA_URL=postgresql://postgres:postgres@db:5432/database_name
      - POSTGRES_PRISMA_URL_NON_POOLING=postgresql://postgres:postgres@db:5432/database_name
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_name
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: always

volumes:
  db_data:



